wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1667839480
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      4: 3.9.13
      5: 0.12.17
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 4
cancer:
  desc: null
  value: KIRP
data_type:
  desc: null
  value: SM
epochs:
  desc: null
  value: 31
lr:
  desc: null
  value: 0.0003
model_type:
  desc: null
  value: L3GCNConv
optim:
  desc: null
  value: ADAM
save:
  desc: null
  value: ./new_res/KIRP/SM/L3GCNConv/ADAM_0.0003/
