wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668528461.251038
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      3:
      - 2
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 3
cancer:
  desc: null
  value: KIRP
data_type:
  desc: null
  value: SM
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.0003
model_type:
  desc: null
  value: L2EGConv
optim:
  desc: null
  value: ADAM
save:
  desc: null
  value: ./new_res/KIRP/SM/L2EGConv/ADAM_0.0003/
