wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668369709
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      4: 3.9.13
      5: 0.12.17
      8:
      - 5
batch_size:
  desc: null
  value: 3
cancer:
  desc: null
  value: KIRP
data_type:
  desc: null
  value: SM_miss
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.0003
model_type:
  desc: null
  value: L3SGConv
optim:
  desc: null
  value: ADAM
save:
  desc: null
  value: ./new_res/KIRP/SM_miss/L3SGConv/ADAM_0.0003/
