main:
  omics_file: "data/raw/miss/kirp_sm_miss251_csn.csv"
  network_file: "data/network/CancerSubnetwork.txt"
  survival_file: "../data/survival/survival_KIRP.csv"
  log_save: "./clustering_logs/" 
  learning_rate: 3e-4
  num_epochs: 100
  batch_size: 3
  num_features: 1
  out_channels: 1
  rank: 2

meta:
  cancer: KIRP
  omic: SM_miss

model:
  gmodel: 
  - L2GCNConv
  - L3GCNConv
  - L3SAGEConv
  - L2SAGEConv
  - L3GraphConv
  - L2GraphConv
  - L3GatedGraphConv
  - L2GatedGraphConv
  - L3GATv2Conv
  - L2GATv2Conv
  - L3GravNetConv
  - L2GravNetConv
  - L3ChebConv
  - L2ChebConv
  - L3ResGatedGraphConv
  - L2ResGatedGraphConv
  - L3TransformerConv
  - L2TransformerConv
  - L3AGNNConv
  - L2AGNNConv
  - L3TAGConv
  - L2TAGConv
  - L3ARMAConv
  - L2ARMAConv


  optim: ADAM
  lossfn: focal
  wandb: EXPERIMENTAL_RUNS_PART1_MISS